name: demo-uib
services:
  bonita:
    image: demo-from-scratch-production:0.0.1
    hostname: bonita
    volumes:
      #Modify with a valid production environment licence (not studio)
      - ~/bonita-lic/10.2:/opt/bonita_lic/
    ports:
      - 8080:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=example
      - DB_VENDOR=postgres
      - DB_HOST=bonita-db
      - JMX_REMOTE_ACCESS=true
      - DB_PORT=5432
      - DB_NAME=bonita
      - DB_USER=bonita
      - DB_PASS=bpm
      - BIZ_DB_NAME=business_data
      - BIZ_DB_USER=business_data
      - BIZ_DB_PASS=bpm
    depends_on:
      bonita-db:
        condition:
          service_healthy
  bonita-db:
    image: bonitasoft/bonita-postgres:latest
    ports:
      - 5432:5432
  bonita-uib:
    image: demo-uib:1.0.0
    container_name: bonita-ui-builder
    environment:
      BONITA_API_URL: http://bonita:8080/bonita/API
      BONITA_DEV_MODE: false
    ports:
      - "8090:80"


  # A reverse proxy used to communicate between Bonita UI Builder and a Bonita Runtime
  bonita-ui-proxy:
    #image: bonitasoft.jfrog.io/docker/bonita-ui-proxy:1.2.0
    #Image for internal usage
    image: bonitasoft.jfrog.io/docker-releases/bonita-ui-proxy:1.2.0
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
